sudo: false
cache: pip

language: python

python:
  - "2.7"
env:
  global:
    # travis for docs build
    - secure: 1r8MhN8yvgC982brnDvNvxNpP5XAQjebBeX2lQBTCP2TFK1FXC1tBTlP7DIqgbFkO7UvVmyFb56S1UwyP2nz/dASvvVmIJtMBUpZPG21o5JLyHkfCK9EimbilVcxaQkJWTFD67GfaKYe3RNg7F+i36ymyWE6HrosnxbQFqIAVsOjPbGZPrNNVruIOToR6RVVpwC3A1qN6V777C5gwi+1CcI94FgBiQNzQhq9ghp87hq7ixzxbB+Ec0ucNFTr3jho4rdpy0r9EeWV/V+TZjFNrcYDmyYJ6nP8eP4QIvP5c8D2P0MLob+oH2EAjanUgKR5j0/fI/VbGhQy0NXjBp6918CLDru6fxQMYS8nCYTZ8/ZjsTPPp/e8Ts+cS09yFbSP3+sxGcFFmo3nE3P40KsT6e36BGpHQIZVbzjJ6gpBfN04H/5gqJbRwmkfjQQ36I4RCzs1fWdBA8EdNqLjxIDAgcg5hlA3xfIBRADs7y7Ak5mmwNfpDnn+yPKMnpnLTVnoWNWDBaLhRLCyBNTBEKljuic0J2KQdCXmgSDTroZ6QQ4OzmbMltujk6zao9WbQbx5U5j9HxVUQ6segCoU3PJgDWtmkbLrHuKkOmhk3vnlMjFdhVZZfDj3Lmp6t+lo1/XM7tKjOhjjdUDKD/bZX3vIacDrcUw1gqjxGm5pbU4s2Os=

before_install:
  - git clone https://github.com/lmignon/travis-sphinx.git -b refactor-lmi
  - pip install travis-sphinx

script:
  - travis-sphinx build -s doc/source/
  - travis-sphinx deploy
